README.md
=> Add Mark Luntzel

README.md
=> Add Ian Henry

README.md
Inspirationally awesome talk today.  Thanks so much!
=> Adds veloandy to Practitioners

README.md
=> Add Robb Kidd to Practitioners.

index.html
=> "it's" not "its"

README.md
Awesome Talks, Awesome Person - that Adam Jacob guy! Can't wait to see the reruns of the presentation!
=> Committed myself to the path. Hugs to Adam Jacob and cheffriends.

README.md
Adding my name to the list of practitioners.  Inspiring keynote.  thank
you.
=> sign me up

index.html
=> spelling fixes

README.md
=> Can you hear the grasshopper at your feet?

README.md
@adamhjk, your presentations always provide the B12 shot that I need.  So fired up by this.  Bravo sir!
=> add toddmichael to list of practitioners

README.md
Adding Jim Constantine as a practitioner of Chef Style DevOps kung fu
=> please add Jim Constantine as a practitioner 

README.md
please merge fix for Julian/Jim conflict
=> Juliandunn 武术

README.md
=> added myself to the practitioners list

README.md
John Martin is a practitioner of Chef-style DevOps
=> Adding jmartin (tekbuddha)

README.md
Me want's to be #devops ninja...
=> Added myself as Devops wannabe

README.md
=> +David Chou as DevOps practitioner

README.md
Change-Id: I0d6b74c74a9ff31dd43e7110e896b671f489ffae
=> Joined the dojo

README.md
=> I Know Kung Fu

README.md
=> Added Joshua Miller to README.md

README.md
Add my name to the middle of the list. Should the list be alphabetized?
=> Add self to practitioners

README.md
Your Chef style exceeds my Crane style.  Surely there's a Drunken style in here somewhere?
=> The Miyagi Devops Dojo converges with devops-kungfu

README.md
I want my kungfu to grow. I come with a beginner's mind.
=> Adding Franklin Webber to the School

README.md
I wish to be a DevOps Kung-Fu master.
=> Added myself to list.

README.md
Everybody was kung fu fighting. 
Those guys were fast as lightning.
=> Add Dan Webb

index.html
* Stage 4 - Operate -> Stage 5 - Operate
* Stage 5 - Deliver -> Stage 6 - Deliver
=> Project stages are numbered correctly

README.md
Add Jonathan Poole to README.md
=> Add Jonathan Poole

README.md
=> Add Amitraj Budhu

README.md
=> Please add Jesse Adams to practitioners list!

CONTRIBUTING.md, README.md
and adding myself to the list of Practitioners (until my new school emerges)
& removed some unrelated links in the CONTRIBUTING.md
=> Practise makes DevOps..

README.md
=> Adding Rakesh Patel to the README

README.md
Trevor Powell joining the School
=> Added the shaolin monk Trevor Powell

README.md
=> Me me, pick me!

README.md
I want to hang out with the cool kids
=> Adding Nicholas Ng

README.md
=> Reformatting name with hyperlink

README.md
I want to be a DevOps Jedi, too
=> Add my own name to README.md

attribution.html, index.html
Attribution is in the attribution file instead of "original image" links in the presentation.
=> Move attribution to attribution file

README.md
I've been meaning to do this for a while now.  Great presentation, thanks for being awesome!
=> Update README.md to add my name.

README.md
Added myself to list of practitioners and built with Travis
=> New member of the school

README.md
I was about to join for some time... Inspiring talk and ideas worth to practice.
=> Add one more Kung-fu kid..

README.md
=> Carlos merge

README.md
Thank you for formalizing this definition and making "the practice" of DevOps more explicit.
=> add myself to readme

README.md
=> Added Martin Neiiendam to the list of practitioners

index.html
I noticed this typo while @nathenharvey was presenting to a customer :grin:
=> its -> it's (this is really a contraction), and avoid comma splice

README.md
Added John Fitzpatrick to README.md.
=> Added John Fitzpatrick

README.md
Added my information to the list of students.
=> added student Moos3

README.md
=> Added my name to practitioner

README.md
=> Added myself to the readme file.

README.md
=> Added Scott Ford

README.md
=> Added Eduardo Monesi

README.md
I agree with the  Chef style DevOps way of life. I'd like to have my name added to the official list. 
@
=> Chef style DevOps welcomes Andrew S Thompson as a practitioner

index.html
* Remove ChefConf lead-in slide
* Enable the controls
* Add helper text on first slide pointing user to the controls in the lower-right.
=> Better support distribution of the presentation via gh-pages direct link

README.md
Add Ashley Knowles to practitioners list
=> Add Ashley Knowles to practitioners list

README.md
=> Update README.md & add Adrian Suteu

README.md
Enjoyed the talk. Felt compelled to jump in.
=> Add Dan Belling to list of Practitioners

README.md
=> Remove my name from the README

README.md
Signing up as a practitioner :-)
=> Signing up as Chef Style DevOps practicioner

README.md
Please add my name to the practitioners list.
Thanks,
=> Added Tatsuya Suzuki

README.md
=> Add my name to README.md!

README.md
Added my name to the list of practitioners of DevOps KungFu
=> Added Phillip Roberts to README.md

README.md
Was at the recent Dallas DevOpsDays when @nathenharvey invited us to sign this. Passing it along to my company!
=> Signing my name!

README.md
=> Update README.md to add Ryan Brown

README.md
=> Added Karl Fischer

README.md
Adding my name to the list of those who want to drive DevOps practices and methodologies within their organizations.
=> Signing Up!

README.md
Adds my name to the practitioners list
=> :handshake: Enter the Dojo

README.md
Adding name to the DevOps gang :)
=> Adding name into devops kungfu gang :)
